In [2]:
from pymongo import MongoClient
import os
from dotenv import load_dotenv
import pandas as pd

load_dotenv()

True

In [3]:
client = MongoClient('mongodb+srv://sreeshanth_m:mongodb6@website-cluster.cdgpeor.mongodb.net/')
db = client['commerce']
collection = db['products']

products = list(collection.find())

df = pd.DataFrame(products)

In [4]:
df

,_id,name,description,price,image,category,subCategory,color,bestSeller,date,__v
0,6a2c3059871e69022c621f8f,Lily Luxe Bouquet,A handcrafted bouquet featuring elegant pink l...,62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,[Lily],pink,False,1.781281e+12,0
1,6a2c372e5f0ab98e3fc78728,Azure Lily Bouquet,"A breathtaking, premium pipe cleaner bouquet f...",62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,"[Lily, Tulip]",blue,False,1.781283e+12,0
2,6a2c385ccdbb764b7f2214a1,Sunshine Bloom Bouquet,A handmade bouquet featuring bright yellow sun...,62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,[Sunflower],yellow,False,1.781283e+12,0
3,6a2c388bcdbb764b7f2214a3,Crimson Velvet Deluxe Bouquet,"A bold, high-contrast artisanal bouquet showca...",62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,"[Lily, Tulip]",red,False,1.781283e+12,0
4,6a2c38cbcdbb764b7f2214a6,I Love You Bouquet,A bold and passionate handcrafted bouquet feat...,62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,[Lily],red,False,1.781283e+12,0
...,...,...,...,...,...,...,...,...,...,...,...
76,6a2c4b90911767e70cf384f2,Lilac Symphony Bouquet,A handcrafted bouquet featuring lavender lilie...,62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,"[Lily, Tulip, Gerbera]",violet,False,1.781288e+12,0
77,6a2c4bbe911767e70cf384f4,Pink Radiance Bouquet,A handcrafted bouquet featuring vibrant pink t...,62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,"[Lily, Tulip]",red,False,1.781288e+12,0
78,6a2c4be7911767e70cf384f6,Crimson Noir Rose Bouquet,"An incredibly striking, handcrafted bouquet fe...",62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,[Rose],red,True,1.781288e+12,0
79,6a2c4c07911767e70cf384f8,Blue Horizon Bouquet,"An exquisitely artistic, handcrafted bouquet f...",62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,"[Rose, Lily]",blue,False,1.781288e+12,0
80,6a2c4c3b911767e70cf384fa,Amber Radiance Bouquet,A beautifully warm and radiant handcrafted bou...,61,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,[Sunflower],orange,False,1.781288e+12,0

In [5]:
df["subCategory_text"] = df["subCategory"].apply(lambda x: " ".join(x) if isinstance(x,list) else "")

In [6]:
df

,_id,name,description,price,image,category,subCategory,color,bestSeller,date,__v,subCategory_text
0,6a2c3059871e69022c621f8f,Lily Luxe Bouquet,A handcrafted bouquet featuring elegant pink l...,62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,[Lily],pink,False,1.781281e+12,0,Lily
1,6a2c372e5f0ab98e3fc78728,Azure Lily Bouquet,"A breathtaking, premium pipe cleaner bouquet f...",62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,"[Lily, Tulip]",blue,False,1.781283e+12,0,Lily Tulip
2,6a2c385ccdbb764b7f2214a1,Sunshine Bloom Bouquet,A handmade bouquet featuring bright yellow sun...,62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,[Sunflower],yellow,False,1.781283e+12,0,Sunflower
3,6a2c388bcdbb764b7f2214a3,Crimson Velvet Deluxe Bouquet,"A bold, high-contrast artisanal bouquet showca...",62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,"[Lily, Tulip]",red,False,1.781283e+12,0,Lily Tulip
4,6a2c38cbcdbb764b7f2214a6,I Love You Bouquet,A bold and passionate handcrafted bouquet feat...,62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,[Lily],red,False,1.781283e+12,0,Lily
...,...,...,...,...,...,...,...,...,...,...,...,...
76,6a2c4b90911767e70cf384f2,Lilac Symphony Bouquet,A handcrafted bouquet featuring lavender lilie...,62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,"[Lily, Tulip, Gerbera]",violet,False,1.781288e+12,0,Lily Tulip Gerbera
77,6a2c4bbe911767e70cf384f4,Pink Radiance Bouquet,A handcrafted bouquet featuring vibrant pink t...,62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,"[Lily, Tulip]",red,False,1.781288e+12,0,Lily Tulip
78,6a2c4be7911767e70cf384f6,Crimson Noir Rose Bouquet,"An incredibly striking, handcrafted bouquet fe...",62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,[Rose],red,True,1.781288e+12,0,Rose
79,6a2c4c07911767e70cf384f8,Blue Horizon Bouquet,"An exquisitely artistic, handcrafted bouquet f...",62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,"[Rose, Lily]",blue,False,1.781288e+12,0,Rose Lily
80,6a2c4c3b911767e70cf384fa,Amber Radiance Bouquet,A beautifully warm and radiant handcrafted bou...,61,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,[Sunflower],orange,False,1.781288e+12,0,Sunflower

In [7]:
df["features"] = df["category"] + " " + df["description"] + " " + df["name"] + " " + df["subCategory_text"]

In [8]:
df

,_id,name,description,price,image,category,subCategory,color,bestSeller,date,__v,subCategory_text,features
0,6a2c3059871e69022c621f8f,Lily Luxe Bouquet,A handcrafted bouquet featuring elegant pink l...,62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,[Lily],pink,False,1.781281e+12,0,Lily,Bouquet A handcrafted bouquet featuring elegan...
1,6a2c372e5f0ab98e3fc78728,Azure Lily Bouquet,"A breathtaking, premium pipe cleaner bouquet f...",62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,"[Lily, Tulip]",blue,False,1.781283e+12,0,Lily Tulip,"Bouquet A breathtaking, premium pipe cleaner b..."
2,6a2c385ccdbb764b7f2214a1,Sunshine Bloom Bouquet,A handmade bouquet featuring bright yellow sun...,62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,[Sunflower],yellow,False,1.781283e+12,0,Sunflower,Bouquet A handmade bouquet featuring bright ye...
3,6a2c388bcdbb764b7f2214a3,Crimson Velvet Deluxe Bouquet,"A bold, high-contrast artisanal bouquet showca...",62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,"[Lily, Tulip]",red,False,1.781283e+12,0,Lily Tulip,"Bouquet A bold, high-contrast artisanal bouque..."
4,6a2c38cbcdbb764b7f2214a6,I Love You Bouquet,A bold and passionate handcrafted bouquet feat...,62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,[Lily],red,False,1.781283e+12,0,Lily,Bouquet A bold and passionate handcrafted bouq...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,6a2c4b90911767e70cf384f2,Lilac Symphony Bouquet,A handcrafted bouquet featuring lavender lilie...,62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,"[Lily, Tulip, Gerbera]",violet,False,1.781288e+12,0,Lily Tulip Gerbera,Bouquet A handcrafted bouquet featuring lavend...
77,6a2c4bbe911767e70cf384f4,Pink Radiance Bouquet,A handcrafted bouquet featuring vibrant pink t...,62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,"[Lily, Tulip]",red,False,1.781288e+12,0,Lily Tulip,Bouquet A handcrafted bouquet featuring vibran...
78,6a2c4be7911767e70cf384f6,Crimson Noir Rose Bouquet,"An incredibly striking, handcrafted bouquet fe...",62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,[Rose],red,True,1.781288e+12,0,Rose,"Bouquet An incredibly striking, handcrafted bo..."
79,6a2c4c07911767e70cf384f8,Blue Horizon Bouquet,"An exquisitely artistic, handcrafted bouquet f...",62,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,"[Rose, Lily]",blue,False,1.781288e+12,0,Rose Lily,"Bouquet An exquisitely artistic, handcrafted b..."
80,6a2c4c3b911767e70cf384fa,Amber Radiance Bouquet,A beautifully warm and radiant handcrafted bou...,61,[https://res.cloudinary.com/dwtipsm0e/image/up...,Bouquet,[Sunflower],orange,False,1.781288e+12,0,Sunflower,Bouquet A beautifully warm and radiant handcra...

### Tags Creation

In [9]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = model.encode(
    df["features"].tolist(),
    convert_to_tensor=True
)

c:\Users\sreeshanth\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3938.46it/s]

In [10]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(
    embeddings.cpu().numpy()
)

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(embeddings)

In [12]:
similarity_matrix[0]

array([1.        , 0.7822932 , 0.7536328 , 0.8164672 , 0.77449334,
       0.5908382 , 0.44464162, 0.5035716 , 0.32148886, 0.21946567,
       0.87973106, 0.84437317, 0.87422734, 0.7285266 , 0.43228424,
       0.49014258, 0.5481874 , 0.31484026, 0.5274361 , 0.50906104,
       0.6805224 , 0.6041626 , 0.7830585 , 0.5583546 , 0.6043847 ,
       0.8338245 , 0.66476643, 0.675452  , 0.81378937, 0.8379296 ,
       0.77272224, 0.68166506, 0.69925207, 0.32819518, 0.6355965 ,
       0.50360256, 0.5714286 , 0.19910899, 0.12542586, 0.41064173,
       0.3155784 , 0.85691476, 0.81116897, 0.8444693 , 0.8370228 ,
       0.8505126 , 0.8674361 , 0.73137605, 0.58109546, 0.5350138 ,
       0.45652574, 0.6135154 , 0.4748208 , 0.5520227 , 0.45915616,
       0.49513254, 0.4465527 , 0.36955267, 0.26499465, 0.8491219 ,
       0.79849184, 0.5817788 , 0.70974386, 0.83877623, 0.84876895,
       0.7544875 , 0.7887339 , 0.6117673 , 0.77918625, 0.9175683 ,
       0.88903666, 0.89582956, 0.65736455, 0.8068884 , 0.8478464 ,
       0.80372155, 0.8329405 , 0.9075758 , 0.70349205, 0.7980999 ,
       0.73881555], dtype=float32)

In [16]:
def get_related_products_ids(index, top_n=8):
    scores = list(enumerate(similarity_matrix[index]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)

    return[
        str(df.iloc[idx]["_id"]) for idx, score in scores[1:top_n+1]
    ]

In [17]:
for index, row in df.iterrows():
    related_product_ids = get_related_products_ids(index)
    collection.update_one(
        {
            "_id" : row["_id"]
        },
        {
            "$set" : {
                "relatedProducts" : related_product_ids
            }
        }
    )
print("Updated")

Updated